@file:OptIn(InternalComponentsApi::class)

package tech.testsys.web.components.core

import com.vaadin.flow.component.HasStyle
import com.vaadin.flow.component.HasTheme
import com.vaadin.flow.dom.ClassList
import com.vaadin.flow.dom.ThemeList

@InternalComponentsApi
internal enum class CssClass(internal val value: String) {
    Alert("ts-alert"),
    AlertDanger("ts-alert--danger"),
    AlertInfo("ts-alert--info"),
    AlertSuccess("ts-alert--success"),
    AlertWarning("ts-alert--warning"),
    AlertDesc("ts-alert__desc"),
    AlertIcon("ts-alert__icon"),
    AlertText("ts-alert__text"),
    AlertTitle("ts-alert__title"),
    App("ts-app"),
    Avatar("ts-avatar"),
    AvatarT0("ts-avatar--t0"),
    Bell("ts-bell"),
    BellDot("ts-bell__dot"),
    Block("ts-block"),
    BlockDark("ts-block--dark"),
    BlockFilters("ts-block--filters"),
    BlockGrid("ts-block--grid"),
    BlockActions("ts-block__actions"),
    BlockBody("ts-block__body"),
    BlockBodyFlush("ts-block__body--flush"),
    BlockBodyGrid("ts-block__body--grid"),
    BlockEditing("ts-block__editing"),
    BlockFoot("ts-block__foot"),
    BlockHead("ts-block__head"),
    BlockHeadTabs("ts-block__head--tabs"),
    BlockRow("ts-block__row"),
    BlockSub("ts-block__sub"),
    BlockTitle("ts-block__title"),
    DrawerTable("ts-drawer-table"),
    BlockTitles("ts-block__titles"),
    Brand("ts-brand"),
    BrandImage("ts-brand-image"),
    BrandLogo("ts-brand__logo"),
    Btn("ts-btn"),
    BtnBusy("ts-btn--busy"),
    BtnDangerSoft("ts-btn--danger-soft"),
    BtnGhost("ts-btn--ghost"),
    BtnIcon("ts-btn--icon"),
    BtnLink("ts-btn--link"),
    BtnPrimary("ts-btn--primary"),
    BtnProgress("ts-btn--progress"),
    BtnSecondary("ts-btn--secondary"),
    BtnSm("ts-btn--sm"),
    BtnSuccessSoft("ts-btn--success-soft"),
    BtnFill("ts-btn__fill"),
    BtnLabel("ts-btn__label"),
    Chip("ts-chip"),
    ChipMore("ts-chip--more"),
    ChipX("ts-chip__x"),
    ChoiceLabel("ts-choice-label"),
    Code("ts-code"),
    CodeArea("ts-code__area"),
    CodeLines("ts-code__lines"),
    Counter("ts-counter"),
    CounterAccent("ts-counter--accent"),
    CounterDanger("ts-counter--danger"),
    CounterMuted("ts-counter--muted"),
    Crumbs("ts-crumbs"),
    CrumbsSep("ts-crumbs__sep"),
    DateRange("ts-date-range"),
    DateRangePrefix("ts-date-range__prefix"),
    Dialog("ts-dialog"),
    DialogAlert("ts-dialog--alert"),
    DialogMd("ts-dialog--md"),
    DialogLg("ts-dialog--lg"),
    DialogXl("ts-dialog--xl"),
    DialogBody("ts-dialog__body"),
    DialogFoot("ts-dialog__foot"),
    DialogGlyph("ts-dialog__glyph"),
    DialogGrid("ts-dialog__grid"),
    DialogSection("ts-dialog__section"),
    DialogSectionTitle("ts-dialog__section-title"),
    DialogSectionBody("ts-dialog__section-body"),
    DialogHead("ts-dialog__head"),
    DialogStack("ts-dialog__stack"),
    DialogTitle("ts-dialog__title"),
    Download("ts-download"),
    Drop("ts-drop"),
    DropTitle("ts-drop__title"),
    Empty("ts-empty"),
    EmptyError("ts-empty--error"),
    EmptyActions("ts-empty__actions"),
    EmptyDesc("ts-empty__desc"),
    EmptyIcon("ts-empty__icon"),
    EmptyTitle("ts-empty__title"),
    Field("ts-field"),
    FieldDisabled("ts-field--disabled"),
    FieldGrid("ts-field--grid"),
    FieldContent("ts-field__content"),
    FieldLabel("ts-field__label"),
    FieldRequired("ts-field__required"),
    FieldText("ts-field__text"),
    FieldValue("ts-field__value"),
    FieldValueInline("ts-field__value--inline"),
    Filedrop("ts-filedrop"),
    FiledropActions("ts-filedrop__actions"),
    FiledropMeta("ts-filedrop__meta"),
    FiledropStatus("ts-filedrop__status"),
    Filter("ts-filter"),
    FilterOn("ts-filter--on"),
    Footer("ts-footer"),
    FooterBrand("ts-footer__brand"),
    FooterInner("ts-footer__inner"),
    FooterLink("ts-footer__link"),
    FooterLinks("ts-footer__links"),
    FooterLogo("ts-footer__logo"),
    FooterYear("ts-footer__year"),
    H1("ts-h1"),
    Header("ts-header"),
    HeaderSticky("ts-header--sticky"),
    HeaderArrival("ts-header-arrival"),
    HeaderLinkTitle("ts-header-link__title"),
    HeaderMegaTrigger("ts-header-mega-trigger"),
    HeaderMegaGrid("ts-header-mega__grid"),
    HeaderMegaGridSearch("ts-header-mega__grid--search"),
    HeaderMegaHeading("ts-header-mega__heading"),
    HeaderNotification("ts-header-notification"),
    HeaderNotificationUnread("ts-header-notification--unread"),
    HeaderNotificationsEmpty("ts-header-notifications-empty"),
    HeaderNotificationsList("ts-header-notifications-list"),
    HeaderPopupHead("ts-header-popup-head"),
    HeaderReadAll("ts-header-read-all"),
    HeaderSearchStatus("ts-header-search-status"),
    HeaderUserItem("ts-header-user-item"),
    HeaderUserMenu("ts-header-user-menu"),
    HeaderUserName("ts-header-user-name"),
    HeaderUserSeparator("ts-header-user-separator"),
    HeaderAction("ts-header__action"),
    HeaderAvatar("ts-header__avatar"),
    HeaderBar("ts-header__bar"),
    HeaderSearch("ts-header__search"),
    HeaderSpacer("ts-header__spacer"),
    HeaderUser("ts-header__user"),
    Hint("ts-hint"),
    Hstack("ts-hstack"),
    Icon("ts-icon"),
    Kbd("ts-kbd"),
    ListRow("ts-list-row"),
    Lookup("ts-lookup"),
    LookupMany("ts-lookup--many"),
    LookupCount("ts-lookup-count"),
    LookupPager("ts-lookup-pager"),
    LookupSearch("ts-lookup-search"),
    LookupChips("ts-lookup__chips"),
    LookupText("ts-lookup__text"),
    MegaChildren("ts-mega__children"),
    MegaCol("ts-mega__col"),
    MegaColLinked("ts-mega__col--linked"),
    MegaGrid("ts-mega__grid"),
    MegaLink("ts-mega__link"),
    MegaTitle("ts-mega__title"),
    MenuItem("ts-menu__item"),
    MenuItemDanger("ts-menu__item--danger"),
    Mono("ts-mono"),
    MultiselectClear("ts-multiselect__clear"),
    Muted("ts-muted"),
    Nav("ts-nav"),
    NavItem("ts-nav__item"),
    NavItemActive("ts-nav__item--active"),
    NavigationCell("ts-navigation-cell"),
    Num("ts-num"),
    ObscuredValue("ts-obscured-value"),
    Option("ts-option"),
    OptionMeta("ts-option__meta"),
    Options("ts-options"),
    Page("ts-page"),
    PageHead("ts-page-head"),
    PageHeadActions("ts-page-head__actions"),
    PageHeadInner("ts-page-head__inner"),
    PageHeadMeta("ts-page-head__meta"),
    PageHeadTitleRow("ts-page-head__title-row"),
    Pager("ts-pager"),
    PagerBtn("ts-pager__btn"),
    PagerBtnActive("ts-pager__btn--active"),
    PagerGap("ts-pager__gap"),
    PagerLabel("ts-pager__label"),
    Pill("ts-pill"),
    PillActive("ts-pill--active"),
    Pills("ts-pills"),
    Pop("ts-pop"),
    PopoverFoot("ts-popover__foot"),
    PopoverSearch("ts-popover__search"),
    Progress("ts-progress"),
    ProgressAccent("ts-progress--accent"),
    ProgressDanger("ts-progress--danger"),
    ProgressIndeterminate("ts-progress--indeterminate"),
    ProgressNeutral("ts-progress--neutral"),
    ProgressSuccess("ts-progress--success"),
    ProgressThin("ts-progress--thin"),
    ProgressWarning("ts-progress--warning"),
    ProgressBar("ts-progress__bar"),
    RadioGroup("ts-radio-group"),
    Right("ts-right"),
    Row("ts-row"),
    RowClickable("ts-row-clickable"),
    RowEmpty("ts-row-empty"),
    RowNew("ts-row-new"),
    RowSelected("ts-row-selected"),
    Seg("ts-seg"),
    SegSm("ts-seg--sm"),
    Skel("ts-skel"),
    SkelBadge("ts-skel--badge"),
    SkelCircle("ts-skel--circle"),
    SkelRectangle("ts-skel--rectangle"),
    SkelText("ts-skel--text"),
    SkelRow("ts-skel-row"),
    SkelRowLines("ts-skel-row__lines"),
    Skeleton("ts-skeleton"),
    SkeletonBadge("ts-skeleton--badge"),
    SkeletonCircle("ts-skeleton--circle"),
    SkeletonRectangle("ts-skeleton--rectangle"),
    SkeletonText("ts-skeleton--text"),
    Sortable("ts-sortable"),
    Sorted("ts-sorted"),
    Spinner("ts-spinner"),
    SrOnly("ts-sr-only"),
    Status("ts-status"),
    StatusDanger("ts-status--danger"),
    StatusInfo("ts-status--info"),
    StatusNeutral("ts-status--neutral"),
    StatusSuccess("ts-status--success"),
    StatusWarning("ts-status--warning"),
    StatusDot("ts-status__dot"),
    Tab("ts-tab"),
    TabActive("ts-tab--active"),
    Table("ts-table"),
    TableFilters("ts-table-filters"),
    TableFiltersActions("ts-table-filters__actions"),
    TableFiltersApply("ts-table-filters__apply"),
    TableFiltersContent("ts-table-filters__content"),
    TableFiltersFields("ts-table-filters__fields"),
    TableFiltersReset("ts-table-filters__reset"),
    TableFiltersToggle("ts-table-filters__toggle"),
    TableGrid("ts-table-grid"),
    TablePager("ts-table-pager"),
    TableScroll("ts-table-scroll"),
    Tabs("ts-tabs"),
    TabsBare("ts-tabs--bare"),
    TabsLg("ts-tabs--lg"),
    Tag("ts-tag"),
    Timer("ts-timer"),
    TimerChip("ts-timer--chip"),
    TimerDanger("ts-timer--danger"),
    TimerNum("ts-timer__num"),
    TimerPart("ts-timer__part"),
    TimerParts("ts-timer__parts"),
    TimerTile("ts-timer__tile"),
    TimerTiles("ts-timer__tiles"),
    TimerUnit("ts-timer__unit"),
    Toast("ts-toast"),
    ToastError("ts-toast--error"),
    ToastInfo("ts-toast--info"),
    ToastSuccess("ts-toast--success"),
    ToastWarning("ts-toast--warning"),
    ToastClose("ts-toast__close"),
    ToastDesc("ts-toast__desc"),
    ToastIcon("ts-toast__icon"),
    ToastText("ts-toast__text"),
    ToastTitle("ts-toast__title"),
    Trigger("ts-trigger"),
    TriggerOpen("ts-trigger--open"),
    Verdict("ts-verdict"),
    VerdictScore("ts-verdict--score"),
    VerdictLabel("ts-verdict__label"),
    Vstack("ts-vstack"),
    TagMono("ts-tag--mono"),
    TagDark("ts-tag--dark"),
    TagUp("ts-tag--up"),
    TagDown("ts-tag--down"),
}

@InternalComponentsApi
internal enum class CssTheme(internal val value: String) {
    Dialog("ts-dialog"),
    Drawer("ts-drawer"),
    HeaderArrival("ts-header-arrival"),
    HeaderMega("ts-header-mega"),
    HeaderMenuSearch("ts-header-menu-search"),
    HeaderNotificationsPopup("ts-header-notifications-popup"),
    HeaderPopup("ts-header-popup"),
    HeaderUserPopup("ts-header-user-popup"),
    Menu("ts-menu"),
    Popover("ts-popover"),
    Toast("ts-toast"),
}

@InternalComponentsApi
internal fun HasStyle.addClassName(value: CssClass) = addClassName(value.value)

@InternalComponentsApi
internal fun HasStyle.addClassNames(vararg values: CssClass) = addClassNames(*values.map { value -> value.value }.toTypedArray())

@InternalComponentsApi
internal fun HasStyle.removeClassName(value: CssClass): Boolean = removeClassName(value.value)

@InternalComponentsApi
internal fun HasStyle.hasClassName(value: CssClass): Boolean = hasClassName(value.value)

@InternalComponentsApi
internal fun HasStyle.removeClassNames(vararg values: CssClass) = removeClassNames(*values.map { value -> value.value }.toTypedArray())

@InternalComponentsApi
internal fun HasStyle.setClassName(value: CssClass) = setClassName(value.value)

@InternalComponentsApi
internal fun HasStyle.setClassName(value: CssClass, present: Boolean) = setClassName(value.value, present)

@InternalComponentsApi
internal fun ClassList.add(value: CssClass): Boolean = add(value.value)

@InternalComponentsApi
internal fun ClassList.remove(value: CssClass): Boolean = remove(value.value)

@InternalComponentsApi
internal fun ClassList.contains(value: CssClass): Boolean = contains(value.value)

@InternalComponentsApi
internal fun ClassList.set(value: CssClass, present: Boolean): Boolean = set(value.value, present)

@InternalComponentsApi
internal fun HasTheme.addThemeName(value: CssTheme) = addThemeName(value.value)

@InternalComponentsApi
internal fun ThemeList.add(value: CssTheme): Boolean = add(value.value)
