glossary.user={case, select,\
    nom {{count, plural,\
        one   {Пользователь}\
        few   {Пользователя}\
        many  {Пользователей}\
        other {Пользователя}\
    }}\
    gen {{count, plural,\
        one   {Пользователя}\
        few   {Пользователей}\
        many  {Пользователей}\
        other {Пользователя}\
    }}\
    dat {{count, plural,\
        one   {Пользователю}\
        few   {Пользователям}\
        many  {Пользователям}\
        other {Пользователю}\
    }}\
    acc {{count, plural,\
        one   {Пользователя}\
        few   {Пользователей}\
        many  {Пользователей}\
        other {Пользователя}\
    }}\
    ins {{count, plural,\
        one   {Пользователем}\
        few   {Пользователями}\
        many  {Пользователями}\
        other {Пользователем}\
    }}\
    loc {{count, plural,\
        one   {Пользователе}\
        few   {Пользователях}\
        many  {Пользователях}\
        other {Пользователе}\
    }}\
    other {Пользователь}\
}
glossary.task={case, select,\
    nom {{count, plural,\
        one   {Задача}\
        few   {Задачи}\
        many  {Задач}\
        other {Задачи}\
    }}\
    gen {{count, plural,\
        one   {Задачи}\
        few   {Задач}\
        many  {Задач}\
        other {Задачи}\
    }}\
    dat {{count, plural,\
        one   {Задаче}\
        few   {Задачам}\
        many  {Задачам}\
        other {Задаче}\
    }}\
    acc {{count, plural,\
        one   {Задачу}\
        few   {Задачи}\
        many  {Задач}\
        other {Задачи}\
    }}\
    ins {{count, plural,\
        one   {Задачей}\
        few   {Задачами}\
        many  {Задачами}\
        other {Задачей}\
    }}\
    loc {{count, plural,\
        one   {Задаче}\
        few   {Задачах}\
        many  {Задачах}\
        other {Задаче}\
    }}\
    other {Задача}\
}

task.result={count, number, Вы решили #}{glossaryTask}
task.deadline.in_days={days, plural, one {через # день} few {через # дня} many {через # дней} other {через # дней}}
task.deadline.passed=Дедлайн прошёл
task.score.percent=Результат: {value, number, percent}
