testsys.grading.max-attempts=3
testsys.grading.total-timeout=PT30M
testsys.grading.rpc-timeout=PT10M
testsys.grading.status-timeout=PT5S
testsys.grading.poll-interval=PT5S
testsys.grading.max-message-bytes=400000000
testsys.grading.should-record-video=true
