package tech.testsys.infra.database.codegen.jpa

import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * KSP processor that emits a `<EntityName>Fields` object containing string
 * constants for every JPA-mapped property of every `@jakarta.persistence.Entity`.
 *
 * Tolerant by design: never fails the build. See spec for the contract.
 *
 * @since %CURRENT_VERSION%
 */
internal class FieldNamesProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        resolver.getSymbolsWithAnnotation(JPA_ENTITY_FQN)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { processEntity(it) }
        return emptyList()
    }

    private fun processEntity(entity: KSClassDeclaration) {
        val properties = collectPropertiesInOrder(entity).filterNot(::hasTransient)
        val compositeIdType = resolveCompositeIdType(entity)
        emitFieldsObject(entity, properties, compositeIdType)
    }

    /**
     * Walks the superclass chain root-first and concatenates the
     * `getDeclaredProperties()` of each class. This produces a stable order
     * independent of any KSP iteration quirks: deepest ancestor's properties
     * first, then closer ancestors, finally the entity's own properties in
     * primary-constructor / body declaration order.
     */
    private fun collectPropertiesInOrder(decl: KSClassDeclaration): List<KSPropertyDeclaration> {
        val chain = mutableListOf<KSClassDeclaration>()
        var current: KSClassDeclaration? = decl
        while (current != null && current.qualifiedName?.asString() != KOTLIN_ANY_FQN) {
            chain.add(current)
            current = current.superTypes
                .map { it.resolve().declaration }
                .filterIsInstance<KSClassDeclaration>()
                .firstOrNull { it.classKind == ClassKind.CLASS }
        }
        return chain.reversed().flatMap { it.getDeclaredProperties().toList() }
    }

    private fun hasTransient(prop: KSPropertyDeclaration): Boolean = prop.annotations.any {
        it.annotationType.resolve().declaration.qualifiedName?.asString() == JPA_TRANSIENT_FQN
    }

    /**
     * Resolves the composite-id type argument `T` of `CompositeJpaEntity<T>` if
     * the entity directly extends it. Returns `null` otherwise. Inspects only
     * direct supertypes — matches the behaviour of
     * [CompositeKeyConstructorProcessor.resolveCompositeIdType].
     */
    private fun resolveCompositeIdType(entity: KSClassDeclaration): KSClassDeclaration? {
        val supertype = entity.superTypes
            .map { it.resolve() }
            .firstOrNull { it.declaration.qualifiedName?.asString() == COMPOSITE_JPA_ENTITY_FQN }
        if (supertype == null) return null
        return supertype.arguments.firstOrNull()
            ?.type?.resolve()?.declaration as? KSClassDeclaration
    }

    private fun emitFieldsObject(
        entity: KSClassDeclaration,
        properties: List<KSPropertyDeclaration>,
        compositeIdType: KSClassDeclaration?,
    ) {
        val objectName = "${entity.simpleName.asString()}Fields"
        val objectBuilder = TypeSpec.objectBuilder(objectName)
        for (prop in properties) {
            val propName = prop.simpleName.asString()
            objectBuilder.addProperty(
                PropertySpec.builder(toScreamingSnakeCase(propName), String::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%S", propName)
                    .build(),
            )
        }

        if (compositeIdType != null) {
            val nested = buildNestedIdObject(compositeIdType, reportNode = entity)
            if (nested != null) {
                objectBuilder.addType(nested)
            }
        }

        val file = FileSpec.builder(
            packageName = entity.packageName.asString(),
            fileName = "${entity.simpleName.asString()}\$Fields",
        )
            .indent("    ")
            .addFileComment("Generated by FieldNamesProcessor. Do not edit.")
            .addType(objectBuilder.build())
            .build()

        file.writeTo(
            codeGenerator = codeGenerator,
            aggregating = false,
            originatingKSFiles = listOfNotNull(entity.containingFile),
        )
    }

    /**
     * Builds a nested `object Id { ... }` with one `const val` per
     * primary-constructor parameter of the composite id type. Returns `null`
     * (and logs a warning) if the id type has no primary constructor — the
     * outer object is still emitted by the caller.
     */
    private fun buildNestedIdObject(idType: KSClassDeclaration, reportNode: KSClassDeclaration): TypeSpec? {
        val ctor = idType.primaryConstructor
        if (ctor == null) {
            logger.warn(
                "FieldNamesProcessor: composite id ${idType.simpleName.asString()} has no primary constructor; " +
                    "skipping nested Id object",
                reportNode,
            )
            return null
        }
        val nested = TypeSpec.objectBuilder("Id")
        for (param in ctor.parameters) {
            val name = param.name?.asString() ?: continue
            nested.addProperty(
                PropertySpec.builder(toScreamingSnakeCase(name), String::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%S", name)
                    .build(),
            )
        }
        return nested.build()
    }

    /**
     * Converts a `camelCase` or `PascalCase` Kotlin identifier into
     * `SCREAMING_SNAKE_CASE`, required by detekt's `ObjectPropertyNaming`
     * rule for `const val`.
     *
     * Examples:
     *  - `authorId`               -> `AUTHOR_ID`
     *  - `gradingErrorDescription` -> `GRADING_ERROR_DESCRIPTION`
     *  - `URLValue`               -> `URL_VALUE`
     */
    private fun toScreamingSnakeCase(name: String): String = name
        .replace(Regex("([a-z0-9])([A-Z])"), "$1_$2")
        .replace(Regex("([A-Z]+)([A-Z][a-z])"), "$1_$2")
        .uppercase()

    private companion object {

        const val JPA_ENTITY_FQN = "jakarta.persistence.Entity"
        const val JPA_TRANSIENT_FQN = "jakarta.persistence.Transient"
        const val KOTLIN_ANY_FQN = "kotlin.Any"
        const val COMPOSITE_JPA_ENTITY_FQN = "tech.testsys.infra.database.jpa.entity.CompositeJpaEntity"
    }
}
