package tech.testsys.infra.database.codegen.jpa

import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.symbol.ClassKind
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSPropertyDeclaration
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.ksp.writeTo

/**
 * Emits a `<Entity>Fields` object with a `const val` property name per non-transient property of every `@Entity`,
 * plus a nested `Id` object for `CompositeJpaEntity` subclasses. Never fails the build.
 */
internal class FieldNamesProcessor(
    private val codeGenerator: CodeGenerator,
    private val logger: KSPLogger,
) : SymbolProcessor {

    override fun process(resolver: Resolver): List<KSAnnotated> {
        resolver.getSymbolsWithAnnotation(JpaFqns.JPA_ENTITY)
            .filterIsInstance<KSClassDeclaration>()
            .forEach { processEntity(it) }
        return emptyList()
    }

    private fun processEntity(entity: KSClassDeclaration) {
        val properties = collectPropertiesInOrder(entity).filterNot(::hasTransient)
        val compositeIdType = resolveCompositeIdType(entity)
        emitFieldsObject(entity, properties, compositeIdType)
    }

    /** Properties of [decl] and its superclasses, root-first and in declaration order, so the output is stable. */
    private fun collectPropertiesInOrder(decl: KSClassDeclaration): List<KSPropertyDeclaration> {
        val chain = mutableListOf<KSClassDeclaration>()
        var current: KSClassDeclaration? = decl
        while (current != null && current.qualifiedName?.asString() != JpaFqns.KOTLIN_ANY) {
            chain.add(current)
            current = current.superTypes
                .map { it.resolve().declaration }
                .filterIsInstance<KSClassDeclaration>()
                .firstOrNull { it.classKind == ClassKind.CLASS }
        }
        return chain.reversed().flatMap { it.getDeclaredProperties().toList() }
    }

    private fun hasTransient(prop: KSPropertyDeclaration): Boolean = prop.annotations.any {
        it.annotationType.resolve().declaration.qualifiedName?.asString() == JpaFqns.JPA_TRANSIENT
    }

    /** Type argument `T` when [entity] directly extends `CompositeJpaEntity<T>`, otherwise `null`. */
    private fun resolveCompositeIdType(entity: KSClassDeclaration): KSClassDeclaration? {
        val supertype = entity.superTypes
            .map { it.resolve() }
            .firstOrNull { it.declaration.qualifiedName?.asString() == JpaFqns.COMPOSITE_JPA_ENTITY }
        if (supertype == null) return null
        return supertype.arguments.firstOrNull()
            ?.type?.resolve()?.declaration as? KSClassDeclaration
    }

    private fun emitFieldsObject(
        entity: KSClassDeclaration,
        properties: List<KSPropertyDeclaration>,
        compositeIdType: KSClassDeclaration?,
    ) {
        val objectName = "${entity.simpleName.asString()}Fields"
        val objectBuilder = TypeSpec.objectBuilder(objectName)
        for (prop in properties) {
            val propName = prop.simpleName.asString()
            objectBuilder.addProperty(
                PropertySpec.builder(toScreamingSnakeCase(propName), String::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%S", propName)
                    .build(),
            )
        }

        if (compositeIdType != null) {
            val nested = buildNestedIdObject(compositeIdType, reportNode = entity)
            if (nested != null) {
                objectBuilder.addType(nested)
            }
        }

        val file = FileSpec.builder(
            packageName = entity.packageName.asString(),
            fileName = "${entity.simpleName.asString()}\$Fields",
        )
            .indent("    ")
            .addFileComment("Generated by FieldNamesProcessor. Do not edit.")
            .addType(objectBuilder.build())
            .build()

        file.writeTo(
            codeGenerator = codeGenerator,
            aggregating = false,
            originatingKSFiles = listOfNotNull(entity.containingFile),
        )
    }

    /** Nested `object Id` with a constant per primary constructor parameter of [idType]; `null` with a warning if it has none. */
    private fun buildNestedIdObject(idType: KSClassDeclaration, reportNode: KSClassDeclaration): TypeSpec? {
        val ctor = idType.primaryConstructor
        if (ctor == null) {
            logger.warn(
                "FieldNamesProcessor: composite id ${idType.simpleName.asString()} has no primary constructor; " +
                    "skipping nested Id object",
                reportNode,
            )
            return null
        }
        val nested = TypeSpec.objectBuilder("Id")
        for (param in ctor.parameters) {
            val name = param.name?.asString() ?: continue
            nested.addProperty(
                PropertySpec.builder(toScreamingSnakeCase(name), String::class)
                    .addModifiers(KModifier.CONST)
                    .initializer("%S", name)
                    .build(),
            )
        }
        return nested.build()
    }

    /** `camelCase` to `SCREAMING_SNAKE_CASE` (`URLValue` becomes `URL_VALUE`), as detekt requires for `const val`. */
    private fun toScreamingSnakeCase(name: String): String = name
        .replace(Regex("([a-z0-9])([A-Z])"), "$1_$2")
        .replace(Regex("([A-Z]+)([A-Z][a-z])"), "$1_$2")
        .uppercase()
}
