function CabinetScreen({ route, go, state, actor, selection, updateSelection, searchQuery, onSearch }) {
  const { Page, PageHead, Row, Slot, SlotRow, Block, Button, DataTable, EmptyState, Verdict, StatusBadge, DownloadButton } = window.TS;
  const cabinet = window.PrototypeNavigation.cabinetDefinitions.find(item => item.key === route.cabinetKey);
  const objects = window.DemoModel.getCabinetObjects(state, actor);
  const choose = (key, id) => updateSelection({ [key]: id });
  const nameColumns = [{ key: 'id', title: 'ID', width: 'narrow', mono: true }, { key: 'name', title: 'Название', width: 'fill' }];
  const selectionInfo = (items, key) => items.find(item => item.id === selection[key]) || items[0];
  const statusLabel = status => window.DemoModel.solutionStatusLabels[status] || status;
  const statusTone = status => ['Error', 'Timeout'].includes(status) ? 'danger' : 'info';
  const empty = <EmptyState title="Нет доступных объектов" description="В этом демонстрационном контексте список пуст." action={<Button onClick={() => go(window.PrototypeNavigation.getCabinetRoute(cabinet.key))}>Вернуться в обзор</Button>} />;
  const info = (title, fields) => <Block grid title={title}><PrototypeInfoFields fields={fields} /></Block>;
  const table = (title, items, columns, key, onOpen) => <Block title={title} flush><div className="ts-table-scroll"><DataTable rows={items} columns={[...columns, { key: 'open', title: 'Действие', width: 'medium', render: item => <Button size="sm" variant="secondary" onClick={() => { choose(key, item.id); onOpen?.(item); }}>Открыть сведения</Button> }]} empty={empty} /></div></Block>;
  let content;
  if (route.sectionKey === 'overview') content = <>
    <Row><Slot span={16}><SlotRow><Block span={16} grid title="Сведения о кабинете"><PrototypeInfoFields columns={16} fields={[{ label: 'Псевдоним', value: actor.alias }, { label: 'Роль', value: actor.role }, { label: 'Сообщество', value: objects.communities.map(item => item.name).join(', ') }, { label: 'Контекст', value: actor.id === state.sessionUserId ? 'Пользователь текущего входа' : 'Демонстрационный пользователь' }, { label: 'Последний вход', value: actor.lastLogin, mono: true }]} /><p style={{ gridColumn: '1 / -1' }}>{cabinet.purpose}</p></Block></SlotRow></Slot><Slot span={8}><SlotRow><Block span={8} title="Разделы кабинета">{cabinet.sections.filter(([key]) => key !== 'overview').map(([key, label]) => <Button key={key} variant="secondary" onClick={() => go(`${cabinet.key}.${key}`)}>{label}</Button>)}</Block></SlotRow></Slot></Row>
    {objects.competitions.length ? info('Контекст соревнования', [{ label: 'Соревнование', value: objects.competitions.map(item => item.name).join(', ') }, { label: 'Доступные туры', value: objects.tours.length, mono: true }]) : null}
    {cabinet.key === 'organizer' ? info('Собственные соревнования', [{ label: 'Количество', value: objects.competitions.length, mono: true }]) : null}
    {cabinet.key === 'student' ? info('Классы', [{ label: 'Количество классов', value: objects.classes.length, mono: true }, { label: 'Доступные туры', value: objects.tours.length, mono: true }]) : null}
  </>;
  else if (cabinet.key === 'developer') {
    if (route.sectionKey === 'resources') {
      const resource = selectionInfo(objects.resources, 'resourceId');
      content = <>{table('Доступные ресурсы', objects.resources, [...nameColumns, { key: 'modifiedAt', title: 'Изменён', width: 'medium', mono: true }], 'resourceId')}{resource ? <>{info('Ресурс', [{ label: 'ID', value: resource.id, mono: true }, { label: 'Название', value: resource.name }, { label: 'Тип', value: resource.category }, { label: 'Файл', value: resource.fileName, mono: true }])}<Block title="История изменений" flush><DataTable rowKey="modifiedAt" rows={resource.history} columns={[{ key: 'modifiedAt', title: 'Изменён', width: 'medium', mono: true }, { key: 'fileName', title: 'Файл', width: 'wide', mono: true }, { key: 'comment', title: 'Комментарий', width: 'fill' }, { key: 'download', title: 'Версия', render: revision => <DownloadButton size="sm" onClick={() => window.DemoModel.downloadDemoFile(revision.fileName, 'TestSys demo resource\n' + revision.comment)} /> }]} /></Block><Block title="Отдельный пример редактора"><a href="../../components/forms/forms.card.html">Открыть локальный редактор ресурса в каталоге</a></Block></> : null}</>;
    } else if (route.sectionKey === 'tasks') {
      const task = selectionInfo(objects.tasks, 'taskId');
      content = <>{table('Доступные задачи', objects.tasks, nameColumns, 'taskId')}{task ? info('Задача', [{ label: 'ID', value: task.id, mono: true }, { label: 'Название', value: task.name }, { label: 'Состояние', value: window.DemoModel.taskStateLabels[task.state] || task.state }, { label: 'Версии TRIK Studio', value: task.trikVersions.join(', '), mono: true }, { label: 'Описание', value: task.description, multiline: true }]) : null}</>;
    } else {
      const tour = selectionInfo(objects.tours, 'tourId');
      content = <>{table('Доступные туры', objects.tours, nameColumns, 'tourId')}{tour ? <>{info('Тур', [{ label: 'ID', value: tour.id, mono: true }, { label: 'Название', value: tour.name }, { label: 'Сообщества', value: tour.communityIds.map(id => state.communities.find(item => item.id === id).name).join(', ') }])}<Block title="Задачи тура" flush><DataTable rows={state.tasks.filter(task => tour.taskIds.includes(task.id))} columns={nameColumns} /></Block></> : null}</>;
    }
  } else if (cabinet.key === 'judge') {
    const solution = selectionInfo(objects.solutions, 'solutionId');
    const columns = [{ key: 'id', title: 'ID', width: 'narrow', mono: true }, { key: 'fileName', title: 'Файл', width: 'fill' }, { key: 'status', title: 'Проверка', width: 'medium', render: item => item.status === 'Checked' ? <Verdict score={item.score} label="баллов" /> : <StatusBadge tone={statusTone(item.status)}>{statusLabel(item.status)}</StatusBadge> }];
    content = <>{route.sectionKey === 'solutions' ? table('Решения учеников и участников', objects.solutions, columns, 'solutionId', () => go('judge.result')) : null}{solution ? <>{info('Результат проверки', [{ label: 'Решение', value: solution.id, mono: true }, { label: 'Файл', value: solution.fileName, mono: true }, { label: 'Отправлено', value: solution.submittedAt, mono: true }, { label: 'Логи проверки', value: solution.status === 'Checked' ? 'Демонстрационная проверка завершена' : 'Материалы проверки отсутствуют', multiline: true }, { label: 'Видеозапись', value: 'Не приложена к этому демонстрационному решению' }])}<Block title="Вердикт">{solution.status === 'Checked' ? <Verdict score={solution.score} label="баллов" /> : <StatusBadge tone={statusTone(solution.status)}>{statusLabel(solution.status)}</StatusBadge>}<Button variant="secondary" onClick={() => go('judge.solutions')}>К списку решений</Button></Block></> : <Block>{empty}</Block>}</>;
  } else if (cabinet.key === 'administrator') {
    const user = selectionInfo(objects.users, 'userId');
    content = <>{route.sectionKey === 'users' ? table('Пользователи своего сообщества', objects.users, [{ key: 'id', title: 'ID', width: 'narrow', mono: true }, { key: 'alias', title: 'Псевдоним', width: 'fill' }, { key: 'lastLogin', title: 'Последний вход', width: 'medium', mono: true }], 'userId', () => go('administrator.user')) : null}{user ? <>{info('Сведения о пользователе', [{ label: 'ID', value: user.id, mono: true }, { label: 'Псевдоним', value: user.alias }, { label: 'Роль', value: user.role }, { label: 'Последний вход', value: user.lastLogin, mono: true }])}<Block><Button variant="secondary" onClick={() => go('administrator.users')}>К списку пользователей</Button></Block></> : <Block>{empty}</Block>}</>;
  } else if (['participant', 'observer'].includes(cabinet.key)) {
    const tour = selectionInfo(objects.tours, 'tourId');
    const task = selectionInfo(objects.tasks.filter(task => tour?.taskIds.includes(task.id)), 'taskId');
    const history = objects.solutions.filter(item => item.taskId === task?.id);
    content = <>{table('Доступные туры', objects.tours, [...nameColumns, { key: 'startsAt', title: 'Начало', width: 'medium', mono: true }, { key: 'endsAt', title: 'Конец', width: 'medium', mono: true }], 'tourId')}{tour ? info('Тур', [{ label: 'Название', value: tour.name }, { label: 'Начало', value: tour.startsAt, mono: true }, { label: 'Конец', value: tour.endsAt, mono: true }, { label: 'Время прохождения', value: tour.durationMinutes + ' минут', mono: true }, ...(cabinet.key === 'participant' ? [{ label: 'Осталось времени', value: Math.floor(tour.remainingSeconds / 60) + ' минут', mono: true }] : [])]) : null}
      {cabinet.key === 'participant' && route.sectionKey === 'solutions' && task ? <><Block title="Задачи тура">{objects.tasks.filter(task => tour.taskIds.includes(task.id)).map(task => <Button key={task.id} variant="secondary" onClick={() => choose('taskId', task.id)}>{task.name}</Button>)}</Block>{info('Задача', [{ label: 'Название', value: task.name }, { label: 'Описание', value: task.description, multiline: true }, { label: 'Лучший балл', value: window.DemoModel.getBestScore(state.solutions, actor.id, task.id) ?? 'Нет проверенных решений', mono: true }])}<Block title="Собственные решения" flush><DataTable rows={history} columns={[{ key: 'submittedAt', title: 'Отправлено', width: 'medium', mono: true }, { key: 'fileName', title: 'Файл', width: 'fill' }, { key: 'score', title: 'Проверка', render: item => item.status === 'Checked' ? <Verdict score={item.score} label="баллов" /> : <StatusBadge tone={statusTone(item.status)}>{statusLabel(item.status)}</StatusBadge> }]} empty={empty} /></Block></> : null}
      {cabinet.key === 'observer' && route.sectionKey === 'results' && tour ? <Block title="Обзор результата" flush><DataTable rows={state.users.filter(user => objects.competitions.some(competition => competition.tourIds.includes(tour.id) && competition.participantIds.includes(user.id)))} columns={[{ key: 'alias', title: 'Участник', width: 'medium' }, ...state.tasks.filter(task => tour.taskIds.includes(task.id)).map(task => ({ key: task.id, title: task.name, render: user => { const score = window.DemoModel.getBestScore(state.solutions, user.id, task.id); return score == null ? 'Нет результата' : <Verdict score={score} />; } }))]} /></Block> : null}
      {cabinet.key === 'participant' && route.sectionKey === 'tours' ? <Block><Button onClick={() => go('participant.solutions')}>Открыть задачи и решения</Button></Block> : null}</>;
  } else content = info(route.title, [{ label: 'Роль', value: actor.role }, { label: 'Сообщество', value: objects.communities.map(item => item.name).join(', ') }, { label: 'Назначение', value: cabinet.purpose, multiline: true }, { label: 'Возможности', value: 'Просмотр назначения роли и сведений о своём сообществе', multiline: true }]);
  return <Page header={<PrototypeHeader searchQuery={searchQuery} onSearch={onSearch} route={route} go={go} state={state} actor={actor} />} head={<PageHead title={route.sectionKey === 'overview' ? cabinet.label : route.title} breadcrumbs={PrototypeBreadcrumbs(route, go)} badges={<StatusBadge tone="info">{actor.role}</StatusBadge>} />}>
    {content}
  </Page>;
}
window.CabinetScreen = CabinetScreen;
