function ProfileScreen({ go, state, dispatch, route, actor: user, selection, updateSelection, searchQuery, onSearch }) {
  const { Page, PageHead, Row, Slot, SlotRow, Block, BlockRow, Field, Input, Select, Button, Verdict, StatusBadge, FileDrop, DownloadButton, DataTable, EmptyState } = window.TS;
  const classes = state.classes.filter(group => group.studentIds.includes(user.id));
  const currentClass = classes.find(group => group.id === selection.classId) || classes[0];
  const tours = state.tours.filter(tour => currentClass?.tourIds.includes(tour.id));
  const tour = tours.find(tour => tour.id === selection.tourId) || tours[0];
  const tasks = state.tasks.filter(task => tour?.taskIds.includes(task.id));
  const task = tasks.find(task => task.id === selection.taskId) || tasks[0];
  const setClassId = classId => updateSelection({ classId, tourId: null, taskId: null });
  const setTourId = tourId => updateSelection({ tourId, taskId: null });
  const setTaskId = taskId => updateSelection({ taskId });
  const [kind, setKind] = React.useState('VisualLanguage');
  const [file, setFile] = React.useState(null);
  const [downloaded, setDownloaded] = React.useState('');
  const [error, setError] = React.useState('');
  React.useEffect(() => { setFile(null); setDownloaded(''); setKind(task?.authorSolutionKinds[0] || 'VisualLanguage'); setError(''); }, [task?.id]);
  const best = task ? window.DemoModel.getBestScore(state.solutions, user.id, task.id) : null;
  const history = state.solutions.filter(solution => solution.userId === user.id && solution.taskId === task?.id);
  const labels = window.DemoModel.solutionStatusLabels;
  const submit = () => { if (!file) { setError('Выберите локальный файл решения'); return; } dispatch({ type: 'submitSolution', userId: user.id, taskId: task.id, kind, fileName: file.name }); setFile(null); setError(''); };
  const profile = route.sectionKey === 'profile';
  const solutions = route.sectionKey === 'solutions';
  return <Page header={<PrototypeHeader searchQuery={searchQuery} onSearch={onSearch} route={route} go={go} state={state} actor={user} />} head={<PageHead title={route.title} breadcrumbs={PrototypeBreadcrumbs(route, go)} badges={<StatusBadge tone="info">{user.role}</StatusBadge>} />}>
    {profile ? <Row><Slot span={24}><SlotRow><Block span={24} grid title="Пользователь"><PrototypeInfoFields fields={[{ label: 'ID', value: user.id, mono: true }, { label: 'Псевдоним', value: user.alias }, { label: 'Почта', value: user.email }, { label: 'Роль', value: user.role }, { label: 'Последний вход', value: user.lastLogin, mono: true }]} /></Block></SlotRow></Slot></Row> : !currentClass ? <Block title="Классы"><EmptyState title="Нет доступных классов" description="У нового демонстрационного ученика пока нет классов." action={<Button onClick={() => go('student.overview')}>В обзор кабинета</Button>} /></Block> : !tour ? <Block title="Классы"><Field label="Класс"><Select value={currentClass.id} onChange={setClassId} options={classes.map(group => ({ value: group.id, label: group.name }))} /></Field><EmptyState title="Туров пока нет" description="В выбранном классе нет доступных туров." action={<Button onClick={() => setClassId(classes[0].id)}>Открыть первый класс</Button>} /></Block> : <>
    <Row><Slot span={8}><SlotRow><Block span={8} grid title="Классы и туры"><BlockRow><div className="ts-vstack" style={{ gridColumn: '1 / -1' }}><Field label="Класс"><Select value={currentClass.id} onChange={setClassId} options={classes.map(group => ({ value: group.id, label: group.name }))} /></Field><Field label="Тур"><Select value={tour.id} onChange={setTourId} options={tours.map(tour => ({ value: tour.id, label: tour.name }))} /></Field><p>{tour.description}</p></div></BlockRow><PrototypeInfoFields columns={8} fields={[{ label: 'Начало', value: tour.startsAt, mono: true }, { label: 'Конец', value: tour.endsAt, mono: true }, { label: 'Длительность', value: tour.durationMinutes + ' минут', mono: true }, { label: 'Осталось', value: Math.floor(tour.remainingSeconds / 60) + ' минут', mono: true }, { label: 'TRIK Studio', value: tour.trikVersion, mono: true }]} /><BlockRow><div className="ts-vstack" style={{ gridColumn: '1 / -1' }}>{tasks.map(item => <Button key={item.id} variant={task.id === item.id ? 'primary' : 'secondary'} onClick={() => setTaskId(item.id)}>{item.name}</Button>)}</div></BlockRow></Block></SlotRow></Slot>
    <Slot span={16}><SlotRow><Block span={16} grid title={task.name}><PrototypeInfoFields columns={16} fields={[{ label: 'ID задачи', value: task.id, mono: true }, { label: 'Лучший балл', value: best == null ? 'Нет проверенных решений' : best, mono: true }]} /><BlockRow><div className="ts-vstack" style={{ gridColumn: '1 / -1' }}><p>{task.description}</p>{!solutions ? <div className="ts-hstack"><DownloadButton labels={{ idle: 'Скачать условие', done: 'Скачать условие' }} onClick={() => { window.DemoModel.downloadDemoFile(task.id + '-statement.txt', task.name + '\n' + task.description + '\nДемонстрационное условие'); setDownloaded('Подготовлено условие: ' + task.id + '-statement.txt'); }} /><DownloadButton labels={{ idle: 'Скачать упражнение', done: 'Скачать упражнение' }} onClick={() => { window.DemoModel.downloadDemoFile(task.id + '-exercise-demo.qrs', 'TestSys demo exercise: ' + task.name); setDownloaded('Подготовлено упражнение: ' + task.id + '-exercise-demo.qrs'); }} /></div> : <Button onClick={() => go('student.study')}>Открыть задачу и отправку решения</Button>}<p role="status">{downloaded}</p></div></BlockRow>
      {!solutions ? <><BlockRow><Field label="Вид решения" labelSize={4} size={12}><Select value={kind} onChange={setKind} options={window.DemoModel.getAllowedSolutionKinds(task).map(value => ({ value, label: window.DemoModel.solutionKindLabels[value] }))} /></Field></BlockRow><BlockRow><Field label="Файл решения" labelSize={4} size={12} required error={error} hint="Локальная демонстрационная проверка; содержимое файла не отправляется на сервер"><FileDrop title={file ? file.name : 'Выберите файл решения'} hint={file ? 'Нажмите, чтобы выбрать другой файл' : '.qrs / .py / .js'} minHeight={100} onSelect={files => { setFile(files[0]); setError(''); }} /></Field></BlockRow><BlockRow><div style={{ gridColumn: '5 / -1' }}><Button onClick={submit}>Отправить решение</Button></div></BlockRow></> : null}
    </Block></SlotRow><SlotRow><Block span={16} title="Мои решения" flush><div className="ts-table-scroll"><DataTable rows={history} columns={[{ key: 'submittedAt', title: 'Отправлено', width: 'medium', mono: true }, { key: 'fileName', title: 'Файл', width: 'fill' }, { key: 'status', title: 'Результат', render: solution => solution.status === 'Checked' ? <Verdict score={solution.score} label="баллов" /> : <StatusBadge tone={['Error', 'Timeout'].includes(solution.status) ? 'danger' : 'info'}>{labels[solution.status]}</StatusBadge> }]} empty={<EmptyState title="Решений пока нет" description="Выберите файл и отправьте первое решение." />} /></div></Block></SlotRow></Slot></Row></>}
  </Page>;
}
window.ProfileScreen = ProfileScreen;
