function OrganizerScreen({ go, state, dispatch, route, actor: user, selection, updateSelection, searchQuery, onSearch }) {
  const { Page, PageHead, Header, Row, Slot, SlotRow, Block, BlockRow, Field, Input, Select, Button, Tabs, DataTable, Verdict, Alert, DownloadButton, EmptyState, StatCard, Dialog, StatusBadge } = window.TS;
  const competitions = state.competitions.filter(c => c.organizerId === user.id);
  const competitionId = selection.competitionId;
  const setCompetitionId = competitionId => updateSelection({ competitionId, tourId: null });
  const competition = competitions.find(c => c.id === competitionId) || competitions[0] || { id: '', name: 'Мои соревнования', participantIds: [], tourIds: [] };
  const tab = route.sectionKey === 'competitions' ? 'overview' : route.sectionKey;
  const setTab = tab => go('organizer.' + (tab === 'overview' ? 'competitions' : tab));
  const [name, setName] = React.useState('');
  const newTourId = selection.newTourId;
  const setNewTourId = newTourId => updateSelection({ newTourId });
  const tourId = selection.tourId;
  const setTourId = tourId => updateSelection({ tourId });
  const [exported, setExported] = React.useState('');
  const [materials, setMaterials] = React.useState(null);
  const tours = state.tours.filter(t => competition.tourIds.includes(t.id));
  const tour = tours.find(t => t.id === tourId) || tours[0];
  const participants = state.users.filter(u => competition.participantIds.includes(u.id));
  const availableTours = window.DemoModel.getOrganizerAvailableTours(state, user).filter(tour => !competition.tourIds.includes(tour.id));
  const chosenNewTour = availableTours.find(t => t.id === newTourId) || availableTours[0];
  const tasks = state.tasks.filter(t => tour?.taskIds.includes(t.id));
  const csv = () => { window.DemoModel.downloadDemoFile('results-' + tour.id + '.csv', window.DemoModel.buildResultsCsv(state, competition.id, tour.id), 'text/csv;charset=utf-8'); setExported('Подготовлена полная матрица: results-' + tour.id + '.csv'); };
  const resultColumns = [{ key: 'id', title: 'ID', width: 'narrow', mono: true }, { key: 'alias', title: 'Псевдоним', width: 'medium' }, ...tasks.map(task => ({ key: task.id, title: task.id + ' · ' + task.name, width: 'wide', render: participant => { const best = window.DemoModel.getBestScore(state.solutions, participant.id, task.id); const count = state.solutions.filter(s => s.userId === participant.id && s.taskId === task.id).length; return <div className="ts-vstack">{best == null ? <span>Нет результата</span> : <Verdict score={best} label="баллов" />}<span className="ts-mono ts-muted">Решений: {count}</span></div>; } }))];
  return <Page header={<PrototypeHeader searchQuery={searchQuery} onSearch={onSearch} route={route} go={go} state={state} actor={user} />} head={<PageHead title={route.title} breadcrumbs={PrototypeBreadcrumbs(route, go)} badges={<StatusBadge tone="info">{user.role}</StatusBadge>} />}>
    <Row><Slot span={24}><SlotRow><Block span={24} grid title="Соревнования организатора"><BlockRow><Field label="Соревнование" labelSize={3} size={9}><Select disabled={!competitions.length} options={competitions.map(c => ({ value: c.id, label: c.name }))} value={competition.id} onChange={setCompetitionId} /></Field><Field label="Новое название" labelSize={3} size={6}><Input value={name} onChange={e => setName(e.target.value)} /></Field><div style={{ gridColumn: 'span 3' }}><Button onClick={() => { dispatch({ type: 'createCompetition', name }); if (name.trim()) setCompetitionId('competition' + state.nextId); }}>Создать</Button></div></BlockRow><PrototypeInfoFields fields={[{ label: 'ID соревнования', value: competition.id || 'Соревнование не выбрано', mono: true }, { label: 'Название', value: competition.id ? competition.name : 'Нет собственных соревнований' }]} /></Block></SlotRow></Slot></Row>
    {state.message ? <Block><Alert tone={state.message.tone} title={state.message.text} /></Block> : null}
    {tab === 'overview' ? <Row><Slot span={12}><SlotRow><Block span={12} grid title="Сведения"><PrototypeInfoFields columns={12} fields={[{ label: 'Организатор', value: user.alias }, { label: 'Участников', value: participants.length, mono: true }, { label: 'Туров', value: tours.length, mono: true }]} /><div className="ts-vstack" style={{ gridColumn: '1 / -1' }}>{!competition.id ? <p>Пока нет собственных соревнований. Укажите название и создайте первое.</p> : null}<p>Соревнование объединяет участников и туры. Результаты доступны по каждому туру.</p><div className="ts-hstack"><Button onClick={() => setTab('participants')}>Открыть участников</Button><Button variant="secondary" onClick={() => setTab('results')}>Открыть результаты</Button></div></div></Block></SlotRow></Slot><Slot span={12}><SlotRow><Block span={12} title="Демонстрационные данные"><p>Создание участников выдаёт каждому отдельный код-доступа. Проверенные решения имеют числовой балл; ошибки и тайм-ауты показаны отдельно.</p><p>Материалы доступны для просмотра. Редактирование ресурсов относится к кабинету разработчика.</p></Block></SlotRow></Slot></Row> : null}
    {tab === 'participants' ? <Block title="Участники" actions={<Button disabled={!competition.id} onClick={() => dispatch({ type: 'createParticipants', competitionId: competition.id })}>Создать 3 участников</Button>} flush><div className="ts-table-scroll"><DataTable rows={participants} columns={[{ key: 'id', title: 'ID', width: 'narrow', mono: true }, { key: 'alias', title: 'Псевдоним', width: 'fill' }, { key: 'lastLogin', title: 'Последний вход', width: 'medium', mono: true }, { key: 'accessCode', title: 'Код-доступа', mono: true }]} empty={<EmptyState title="Участников пока нет" description="Создайте демонстрационных участников с кодами-доступа." action={<Button disabled={!competition.id} onClick={() => dispatch({ type: 'createParticipants', competitionId: competition.id })}>Создать участников</Button>} />} /></div></Block> : null}
    {tab === 'tours' ? <><Block title="Добавить доступный тур"><div className="ts-hstack"><Select aria-label="Доступный тур" value={chosenNewTour?.id} options={availableTours.map(t => ({ value: t.id, label: t.name }))} onChange={setNewTourId} disabled={!availableTours.length} /><Button disabled={!chosenNewTour || !competition.id} onClick={() => dispatch({ type: 'addTour', competitionId: competition.id, tourId: chosenNewTour.id })}>Добавить тур</Button></div>{!availableTours.length ? <p>Все доступные туры уже добавлены.</p> : null}</Block><Block title="Туры соревнования" flush><DataTable rows={tours} columns={[{ key: 'name', title: 'Название', width: 'fill' }, { key: 'startsAt', title: 'Начало', width: 'medium', mono: true }, { key: 'endsAt', title: 'Конец', width: 'medium', mono: true }, { key: 'durationMinutes', title: 'Минут', mono: true }, { key: 'open', title: 'Действие', render: t => <Button size="sm" variant="secondary" onClick={() => { setTourId(t.id); setTab('results'); }}>Результаты тура</Button> }]} empty={<EmptyState title="Туров пока нет" description="Добавьте доступный тур в соревнование." />} /></Block></> : null}
    {tab === 'results' ? tour ? <><Block grid title="Тур и материалы"><BlockRow><div style={{ gridColumn: '1 / -1' }}><Field label="Тур"><Select value={tour.id} onChange={setTourId} options={tours.map(t => ({ value: t.id, label: t.name }))} /></Field></div></BlockRow><PrototypeInfoFields fields={[{ label: 'Название тура', value: tour.name }, { label: 'Начало', value: tour.startsAt, mono: true }, { label: 'Конец', value: tour.endsAt, mono: true }, { label: 'Длительность', value: tour.durationMinutes + ' минут', mono: true }]} /><BlockRow><div className="ts-vstack" style={{ gridColumn: '1 / -1' }}><p>{tour.description}</p><div className="ts-hstack">{tasks.map(task => <Button key={task.id} variant="secondary" onClick={() => setMaterials(task)}>Материалы: {task.name}</Button>)}</div></div></BlockRow></Block><Block title="Участник × задача" subtitle="Лучший балл и количество решений; CSV содержит полную матрицу" flush actions={<DownloadButton labels={{ idle: 'Скачать CSV' }} onClick={csv} />}><p role="status" style={{ padding: 12 }}>{exported}</p><div className="ts-table-scroll"><DataTable rows={participants} columns={resultColumns} empty={<EmptyState title="Нет участников" description="Создайте участников на соответствующей вкладке." action={<Button onClick={() => setTab('participants')}>Открыть участников</Button>} />} /></div></Block></> : <Block><EmptyState title="Нет доступных туров" description="Добавьте тур для просмотра результатов." action={<Button onClick={() => setTab('tours')}>Добавить тур</Button>} /></Block> : null}
    <Dialog open={!!materials} title={materials?.name} onClose={() => setMaterials(null)} footer={<Button variant="secondary" onClick={() => setMaterials(null)}>Закрыть</Button>}><p>{materials?.description}</p><p>Просмотр материалов · редактирование доступно разработчику</p><div className="ts-vstack">{materials ? [{ category: 'Условие', name: materials.id + '-statement.txt' }, { category: 'Полигон', name: materials.id + '-polygon-demo.xml' }, { category: 'Упражнение', name: materials.id + '-exercise-demo.qrs' }, ...materials.authorSolutionKinds.map(kind => ({ category: 'Авторское решение · ' + window.DemoModel.solutionKindLabels[kind], name: materials.id + '-author-demo.' + (kind === 'Python' ? 'py' : kind === 'JavaScript' ? 'js' : 'qrs') }))].map(resource => <div key={resource.name} className="ts-hstack"><span style={{ flex: 1 }}>{resource.category} · <span className="ts-mono">{resource.name}</span></span><DownloadButton size="sm" labels={{ idle: 'Скачать пример' }} onClick={() => { window.DemoModel.downloadDemoFile(resource.name, 'TestSys demo resource: ' + resource.category + '\n' + materials.description); setExported('Подготовлен пример: ' + resource.name); }} /></div>) : null}</div><p role="status">{exported}</p><a href="../../components/forms/forms.card.html">Отдельный пример редактора ресурсов для разработчика</a></Dialog>
  </Page>;
}
window.OrganizerScreen = OrganizerScreen;
