testsys.mail.host=localhost
testsys.mail.port=25
testsys.mail.username=
testsys.mail.password=
testsys.mail.smtp-auth=false
testsys.mail.ssl=false
testsys.mail.starttls=false
testsys.mail.timeout=PT10S
testsys.mail.from=testsys@localhost
testsys.mail.region=RU
testsys.mail.time-zone=Europe/Moscow
