package tech.testsys.web.devapp.demo.model

/** Returns deterministic sample records independent of server time and external operations. */
internal fun demoFixtures(): DemoState = DemoState(
    users = listOf(
        DemoUser(
            id = "student",
            alias = "Анна",
            email = "anna@example.com",
            role = DemoRole.Student,
            accessCode = "STUDENT-2026",
            lastLogin = "01.10.2026 10:00",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "organizer",
            alias = "Ирина",
            email = "irina@example.com",
            role = DemoRole.Organizer,
            accessCode = "ORG-2026",
            lastLogin = "01.10.2026 09:30",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "p1",
            alias = "Участник 1",
            role = DemoRole.Participant,
            accessCode = "PART-101",
            lastLogin = "01.10.2026 10:15",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "p2",
            alias = "Участник 2",
            role = DemoRole.Participant,
            accessCode = "PART-102",
            lastLogin = "—",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "developer",
            alias = "Максим",
            email = "max@example.com",
            role = DemoRole.Developer,
            accessCode = "DEV-2026",
            lastLogin = "01.10.2026 09:00",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "judge",
            alias = "Ольга",
            role = DemoRole.Judge,
            accessCode = "JUDGE-2026",
            lastLogin = "01.10.2026 10:00",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "administrator",
            alias = "Денис",
            role = DemoRole.Administrator,
            accessCode = "ADMIN-2026",
            lastLogin = "01.10.2026 08:30",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "observer",
            alias = "Наблюдатель",
            role = DemoRole.Observer,
            accessCode = "OBSERVER-2026",
            lastLogin = "01.10.2026 10:30",
            communityIds = listOf("community1"),
        ),
        DemoUser(
            id = "supervisor",
            alias = "Супервайзер",
            role = DemoRole.Supervisor,
            accessCode = "SUPERVISOR-2026",
            lastLogin = "01.10.2026 09:15",
            communityIds = listOf("community1"),
        ),
    ),
    communities = listOf(
        DemoCommunity(id = "community1", name = "Лаборатория TRIK"),
        DemoCommunity(id = "public", name = "Публичное сообщество"),
    ),
    resources = listOf(
        DemoResource(
            id = "r1",
            ownerId = "developer",
            taskId = "task1",
            name = "Условие движения по линии",
            category = "Условие",
            fileName = "task1-statement.txt",
            modifiedAt = "30.09.2026 16:00",
            history = listOf(
                DemoHistory(modifiedAt = "30.09.2026 16:00", fileName = "task1-statement.txt", comment = "Уточнена точка финиша"),
            ),
        ),
        DemoResource(
            id = "r2",
            ownerId = "developer",
            taskId = "task1",
            name = "Полигон линии",
            category = "Полигон",
            fileName = "task1-polygon-demo.xml",
            modifiedAt = "30.09.2026 15:00",
            history = listOf(
                DemoHistory(modifiedAt = "30.09.2026 15:00", fileName = "task1-polygon-demo.xml", comment = "Демонстрационная модель мира"),
            ),
        ),
        DemoResource(
            id = "r3",
            ownerId = "developer",
            taskId = "task1",
            name = "Авторское решение Python",
            category = "Авторское Решение",
            fileName = "task1-author-demo.py",
            modifiedAt = "30.09.2026 17:00",
            history = listOf(
                DemoHistory(
                    modifiedAt = "30.09.2026 17:00",
                    fileName = "task1-author-demo.py",
                    comment = "Добавлен демонстрационный вариант",
                ),
            ),
        ),
    ),
    classes = listOf(
        DemoClass(
            id = "c1",
            name = "Робототехника · 8 класс",
            studentIds = listOf("student"),
            tourIds = listOf(
                "t1",
                "t2",
            ),
        ),
        DemoClass(id = "c2", name = "Клуб TRIK · начинающие", studentIds = listOf("student"), tourIds = listOf("t2")),
        DemoClass(id = "c3", name = "Самостоятельная практика", studentIds = listOf("student"), tourIds = emptyList()),
    ),
    competitions = listOf(
        DemoCompetition(
            id = "competition1",
            name = "Осеннее соревнование TRIK",
            organizerId = "organizer",
            communityId = "community1",
            participantIds = listOf(
                "p1",
                "p2",
            ),
            tourIds = listOf("t1"),
        ),
    ),
    tours = listOf(
        DemoTour(
            id = "t1",
            name = "Движение и датчики",
            description = "Два упражнения на движение робота и работу датчика расстояния.",
            startsAt = "01.10.2026 10:00",
            endsAt = "01.10.2026 14:00",
            durationMinutes = 120,
            remainingSeconds = 5400,
            trikVersion = "2026.1",
            taskIds = listOf(
                "task1",
                "task2",
            ),
            ownerId = "developer",
            communityIds = listOf(
                "community1",
                "public",
            ),
        ),
        DemoTour(
            id = "t2",
            name = "Маршруты",
            description = "Планирование маршрута в модели мира TRIK Studio.",
            startsAt = "02.10.2026 10:00",
            endsAt = "02.10.2026 14:00",
            durationMinutes = 90,
            remainingSeconds = 5400,
            trikVersion = "2026.1",
            taskIds = listOf("task3"),
            ownerId = "developer",
            communityIds = listOf("community1"),
        ),
    ),
    tasks = listOf(
        DemoTask(
            id = "task1",
            name = "Движение по линии",
            description = "Проведите робота по линии до финиша.",
            authorSolutionKinds = listOf(
                DemoSolutionKind.VisualLanguage,
                DemoSolutionKind.Python,
            ),
            ownerId = "developer",
            communityIds = listOf(
                "community1",
                "public",
            ),
            state = DemoTaskState.Committed,
            trikVersions = listOf("2026.1"),
        ),
        DemoTask(
            id = "task2",
            name = "Датчик расстояния",
            description = "Остановите робота перед препятствием.",
            authorSolutionKinds = listOf(
                DemoSolutionKind.VisualLanguage,
                DemoSolutionKind.JavaScript,
            ),
            ownerId = "developer",
            communityIds = listOf(
                "community1",
                "public",
            ),
            state = DemoTaskState.Committed,
            trikVersions = listOf("2026.1"),
        ),
        DemoTask(
            id = "task3",
            name = "Обход препятствий",
            description = "Найдите маршрут до целевой точки.",
            authorSolutionKinds = listOf(DemoSolutionKind.VisualLanguage),
            ownerId = "developer",
            communityIds = listOf("community1"),
            state = DemoTaskState.Committed,
            trikVersions = listOf("2026.1"),
        ),
    ),
    solutions = listOf(
        DemoSolution(
            id = "s1",
            userId = "student",
            taskId = "task1",
            fileName = "line.qrs",
            kind = DemoSolutionKind.VisualLanguage,
            submittedAt = "01.10.2026 10:20",
            status = DemoSolutionStatus.Checked,
            score = 0,
        ),
        DemoSolution(
            id = "s2",
            userId = "student",
            taskId = "task1",
            fileName = "line.py",
            kind = DemoSolutionKind.Python,
            submittedAt = "01.10.2026 10:35",
            status = DemoSolutionStatus.Checked,
            score = 72,
        ),
        DemoSolution(
            id = "s3",
            userId = "p1",
            taskId = "task1",
            fileName = "robot.qrs",
            kind = DemoSolutionKind.VisualLanguage,
            submittedAt = "01.10.2026 10:30",
            status = DemoSolutionStatus.Checked,
            score = 85,
        ),
        DemoSolution(
            id = "s4",
            userId = "p2",
            taskId = "task2",
            fileName = "sensor.js",
            kind = DemoSolutionKind.JavaScript,
            submittedAt = "01.10.2026 10:40",
            status = DemoSolutionStatus.Timeout,
            score = null,
        ),
    ),
    observerScopes = listOf(
        DemoObserverScope(userId = "observer", competitionId = "competition1", tourIds = listOf("t1")),
    ),
)
