function CatalogExamples({ group, namespace: N }) {
  const { Button, Block, Row, Slot, SlotRow, Field, BlockRow, Page, Footer, PageHead, Input, Textarea, Select, MultiSelect, CodeEditor, FileDrop, StatusBadge, Verdict, Tag, Counter, Avatar, AvatarGroup, ProgressBar, Timer, Difficulty, StatCard, ContestCard, DataTable, SortableList, Pagination, Header, Tabs, PillTabs, FilterChip, Stepper, Alert, EmptyState, Skeleton, SkeletonRows, Toast, useToasts, Dialog, Drawer, Popover, Menu, Tooltip, IconButton, QuizOption, QuestionNav, DownloadButton } = N;
  const [message, setMessage] = React.useState('Действия ещё не выполнялись');
  const [selected, setSelected] = React.useState([]);
  const [page, setPage] = React.useState(1);
  const [sort, setSort] = React.useState({ key: 'name', dir: 'asc' });
  const [value, setValue] = React.useState('');
  const [emptyCode, setEmptyCode] = React.useState('');
  const [singleDate, setSingleDate] = React.useState(null);
  const [singleCalendar, setSingleCalendar] = React.useState({ year: 2026, month: 9 });
  const [code, setCode] = React.useState('print("TestSys")');
  const [removed, setRemoved] = React.useState(false);
  const [modal, setModal] = React.useState(null);
  const [dialogChoice, setDialogChoice] = React.useState('Условие');
  const [dialogChoices, setDialogChoices] = React.useState(['Условие']);
  const [nested, setNested] = React.useState(false);
  const [downloadState, setDownloadState] = React.useState('idle');
  const [progress, setProgress] = React.useState(0);
  const [fileState, setFileState] = React.useState('empty');
  const [fileName, setFileName] = React.useState('');
  const [resourceCode, setResourceCode] = React.useState('print(42)');
  const [resourceSaved, setResourceSaved] = React.useState('Не сохранено');
  const [extraRows, setExtraRows] = React.useState([]);
  const [items, setItems] = React.useState([{ id: 1, name: 'Первый' }, { id: 2, name: 'Второй' }, { id: 3, name: 'Третий' }]);
  const [toast, toaster] = useToasts();
  const [deadline] = React.useState(() => Date.now() + 20000);
  const remaining = N.useCountdown(deadline);
  const timers = React.useRef([]);
  React.useEffect(() => () => timers.current.forEach(clearTimeout), []);
  const schedule = (f, ms) => timers.current.push(setTimeout(f, ms));
  const clear = () => { timers.current.forEach(clearTimeout); timers.current = []; };
  const download = () => {
    clear(); setDownloadState('preparing'); setProgress(0);
    schedule(() => { setDownloadState('downloading'); setProgress(50); }, 500);
    schedule(() => { setProgress(100); setDownloadState('done'); const url = URL.createObjectURL(new Blob(['TestSys reference demo\n'], { type: 'text/plain' })); const a = document.createElement('a'); a.href = url; a.download = 'testsys-demo.txt'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(() => URL.revokeObjectURL(url), 1000); setMessage('Файл testsys-demo.txt скачан'); }, 1000);
  };
  const upload = files => { clear(); setFileName(files[0].name); setFileState('uploading'); schedule(() => { setFileState('done'); setMessage('Выбран файл: ' + files[0].name); }, 800); };
  const reset = () => { clear(); setMessage('Демонстрация сброшена'); setSelected([]); setPage(1); setSort({ key: 'name', dir: 'asc' }); setRemoved(false); setValue(''); setEmptyCode(''); setSingleDate(null); setSingleCalendar({ year: 2026, month: 9 }); setModal(null); setDialogChoice('Условие'); setDialogChoices(['Условие']); setNested(false); setDownloadState('idle'); setFileState('empty'); setResourceCode('print(42)'); setResourceSaved('Не сохранено'); setExtraRows([]); setItems([{ id: 1, name: 'Первый' }, { id: 2, name: 'Второй' }, { id: 3, name: 'Третий' }]); };
  let content;
  if (group === 'actions') content = <><div className="ts-hstack">{['idle', 'preparing', 'downloading', 'done', 'error'].map(state => <DownloadButton key={state} state={state} progress={50} onClick={download} onCancel={() => { clear(); setDownloadState('idle'); setMessage('Скачивание отменено'); }} />)}<DownloadButton iconOnly state={downloadState} progress={progress} onClick={download} onCancel={() => { clear(); setDownloadState('idle'); }} /></div><DownloadButton state={downloadState} progress={progress} onClick={download} onCancel={() => { clear(); setDownloadState('idle'); setMessage('Скачивание отменено'); }} /><Button variant="secondary" onClick={() => setDownloadState('error')}>Показать ошибку и повтор</Button></>;
  if (group === 'forms') content = <><Row><Slot span={24}><SlotRow><Block span={24} grid title="Горизонтальные поля"><BlockRow><Field label="Длинная подпись поля с переносом" labelSize={4} size={8} required hint="Подсказка под контролом"><Input value={value} onChange={e => setValue(e.target.value)} /></Field><Field label="Ошибка" labelSize={3} size={9} error="Исправьте значение"><Input error defaultValue="anna@mail" /></Field></BlockRow><BlockRow><Field label="Выключено" labelSize={4} size={8} disabled><Input value="Недоступно" readOnly /></Field><Field label="Только чтение" labelSize={3} size={9}><Input readOnly value="Пример" /></Field></BlockRow></Block></SlotRow></Slot></Row>
    <div className="ts-hstack"><Field label="Большое поле"><Input size="lg" /></Field><Field label="Многострочное"><Textarea defaultValue="Текст" /></Field><Field label="Пустой выбор"><Select options={[]} /></Field><Field label="Выбор с ошибкой"><Select error options={['Один', 'Два']} value={value} onChange={setValue} /></Field><Field label="Выбор выключен"><Select disabled options={['Один']} value="Один" /></Field><Field label="Счётчик выбора"><MultiSelect display="count" value={selected} onChange={setSelected} options={['Один', 'Два', 'Три']} /></Field><Field label="Выбор выключен"><MultiSelect disabled value={['Один']} options={['Один', 'Два']} /></Field><Field label="Множественный выбор с ошибкой"><MultiSelect error value={selected} onChange={setSelected} options={['Один', 'Два', 'Три']} /></Field></div>
    <div className="ts-hstack">{[false, true].map(checked => <React.Fragment key={String(checked)}><N.Checkbox checked={checked} disabled label={checked ? 'Выбран и выключен' : 'Выключенный флажок'} /><N.Radio checked={checked} disabled label={checked ? 'Выбранная недоступная роль' : 'Недоступная роль'} /><N.Switch checked={checked} disabled label={checked ? 'Включён и недоступен' : 'Выключен и недоступен'} /></React.Fragment>)}<N.SegmentedControl block size="lg" options={['Первое', 'Второе']} value={value} onChange={setValue} /></div>
    <FileDrop state={fileState} fileName={fileName} fileType="FILE" progress={50} onSelect={upload} /><div className="ts-hstack"><Button onClick={() => setFileState('error')}>Ошибка загрузки</Button><Button variant="secondary" onClick={() => setFileState('empty')}>Выбрать повторно</Button></div><FileDrop state="error" error="Ошибка демонстрационной загрузки" onSelect={upload} />
    <Field label="Редактор кода"><CodeEditor value={code} onChange={setCode} minHeight={100} /></Field><Field label="ReadOnly prefix/suffix"><Input readOnly prefix={<N.Icon name="clock" />} suffix="минут" mono value="120" /></Field><Field label="ReadOnly textarea"><Textarea readOnly value="Длинное информационное значение можно выделить и скопировать." /></Field><Field label="Disabled + readOnly affix" disabled><Input readOnly disabled prefix={<N.Icon name="clock" />} suffix="минут" value="120" /></Field><Field label="Disabled + readOnly textarea" disabled><Textarea readOnly disabled value="Недоступный текст" /></Field><CodeEditor label="Код только для чтения" value="print(0)" readOnly minHeight={80} /><CodeEditor label="Пустой код" value={emptyCode} onChange={setEmptyCode} minHeight={80} /><Block title="DateRangeCalendar · одна дата"><N.DateRangeCalendar range={false} year={singleCalendar.year} month={singleCalendar.month} start={singleDate} today="2026-10-01" onChange={range => setSingleDate(range.start)} onMonthChange={(year, month) => setSingleCalendar({ year, month })} onPrev={() => { const date = new Date(singleCalendar.year, singleCalendar.month - 1, 1); setSingleCalendar({ year: date.getFullYear(), month: date.getMonth() }); }} onNext={() => { const date = new Date(singleCalendar.year, singleCalendar.month + 1, 1); setSingleCalendar({ year: date.getFullYear(), month: date.getMonth() }); }} /><p>Выбрана дата: {singleDate || 'не выбрана'}</p></Block><p>Выбор: {value || 'пусто'} · код: {code} · пустой редактор: {emptyCode || 'пусто'}</p><Block title="Кабинет разработчика · пример редактора ресурса" subtitle="Отдельная демонстрация редактирования текста авторского решения Python; локальная память"><Field label="Ресурс"><Input readOnly value="author-solution-demo.py" /></Field><CodeEditor label="Текст ресурса разработчика" value={resourceCode} onChange={setResourceCode} minHeight={100} /><Button onClick={() => { setResourceSaved(resourceCode); setMessage('Текст демонстрационного ресурса сохранён локально'); }}>Сохранить текст примера</Button><p>Сохранённый текст:</p><pre>{resourceSaved}</pre></Block></>;
  if (group === 'display') content = <><div className="ts-hstack"><Verdict score={0} /><Verdict score={72.5} label="баллов" /><Verdict code="queue" showLabel>Тест 2/5</Verdict>{['success', 'danger', 'info', 'warning', 'neutral', 'draft', 'live'].map(tone => <StatusBadge key={tone} tone={tone} size="sm" dot={false}>{tone}</StatusBadge>)}{!removed ? <Tag onRemove={() => { setRemoved(true); setMessage('Тег удалён'); }}>Удалить тег</Tag> : <Button onClick={() => setRemoved(false)}>Восстановить тег</Button>}<Counter tone="accent">0</Counter><Counter tone="muted">12</Counter></div><div className="ts-hstack">{[24, 32, 40, 48].map(size => <Avatar key={size} size={size} name="Анна Смирнова" />)}<Avatar initials="TR" square tone="dark" /><AvatarGroup names={['Анна', 'Ирина', 'Максим', 'Илья', 'Ольга', 'Денис']} max={2} /></div>{[0, 42, 100].map(v => <ProgressBar key={v} value={v} tone="success" />)}{['accent', 'success', 'warning', 'danger'].map(tone => <ProgressBar key={tone} value={35} tone={tone} thin inverse />)}<ProgressBar indeterminate /><div className="ts-hstack"><Timer seconds={0} /><Timer seconds={30} /><Timer to={deadline} /><Timer seconds={3601} variant="hero" /><Timer seconds={90061} variant="tiles" /><span>useCountdown: {remaining}</span><Difficulty level={1} label={false} /></div><Row>{['up', 'down', 'neutral'].map((trend, index) => <StatCard key={trend} span={8} label={trend} value="42" delta="2" trend={trend === 'neutral' ? undefined : trend} dark={index === 1} />)}</Row><Row>{['neutral', 'live', 'draft'].map(tone => <ContestCard key={tone} span={8} title={'Карточка ' + tone} status={tone} statusTone={tone} tags={['TRIK Studio']} people="3" cta="Открыть тур" onClick={() => setMessage('Открыта карточка ' + tone)} onCta={() => setMessage('Выполнено CTA ' + tone)} />)}</Row></>;
  if (group === 'data') {
    const rows = Array.from({ length: 6 }, (_, i) => ({ id: i + 1, name: ['Анна', 'Ирина', 'Максим', 'Ольга', 'Илья', 'Денис'][i] })).sort((a, b) => (sort.key === 'id' ? a.id - b.id : a.name.localeCompare(b.name)) * (sort.dir === 'asc' ? 1 : -1));
    content = <><DataTable columns={[{ key: 'id', title: 'ID', width: 'narrow', sortable: true }, { key: 'name', title: 'Псевдоним', width: 'fill', sortable: true }]} rows={rows.slice((page - 1) * 2, page * 2)} selectable selected={selected} onSelectChange={setSelected} sort={sort} onSortChange={setSort} newKeys={[1]} compact /><Pagination page={page} total={3} onChange={setPage} /><p>Выбраны: {selected.join(', ') || 'нет'} · страница {page} · сортировка {sort.key} {sort.dir}</p><DataTable columns={[{ key: 'name', title: 'Пустая таблица', width: 'wide' }]} rows={extraRows} empty={<EmptyState title="Нет строк" description="Добавьте демонстрационную строку." action={<Button onClick={() => { setExtraRows([{ id: 'new', name: 'Новая демонстрационная строка' }]); setMessage('Новая строка добавлена'); }}>Добавить строку</Button>} />} /><SortableList items={items} onChange={setItems} renderItem={item => item.name} /><SortableList disabled items={items} renderItem={item => item.name} /><p>Порядок: {items.map(item => item.name).join(' → ')}</p></>;
  }
  if (group === 'layout') content = <><Page style={{ minWidth: 0, minHeight: 300 }} footer={<Footer links={[{ label: 'Каталог', href: '../index.html' }, { label: 'Навигация', href: '../navigation/navigation.card.html' }]} />} head={<PageHead title="Page + минимальный PageHead" />}><Row><Slot span={16}><SlotRow><Block span={8} grid title="BlockRow и Field"><BlockRow><Field label="Подпись" labelSize={3} size={5}><Input /></Field></BlockRow></Block><Block span={8} sunken title="Равная высота">Соседний блок</Block></SlotRow><SlotRow><Block span={12} title="Неполный ряд" footer="Подвал">12 колонок из 16</Block></SlotRow></Slot><Slot span={8}><SlotRow><Block span={8} dark title="Тёмный блок">8 колонок</Block></SlotRow></Slot></Row></Page><PageHead title="Полный PageHead" breadcrumbs={[{ label: 'Каталог', href: '../index.html' }, { label: 'Компоновка' }]} badges={<StatusBadge tone="info">Пример</StatusBadge>} meta="24 колонки" actions={<Button onClick={() => setMessage('Действие PageHead выполнено')}>Действие</Button>} tabs={<Tabs value={value || 'Первое'} onChange={setValue} items={['Первое', 'Второе']} />} /></>;
  if (group === 'navigation') content = <><Header compact brandTarget="sample.home" active="cabinet" items={[{ key: 'home', label: 'Главная', target: 'sample.home' }, { key: 'cabinet', label: 'Кабинет ученика', target: 'sample.overview', menu: { cols: [{ title: 'Разделы', links: [{ key: 'overview', t: 'Обзор', target: 'sample.overview' }, { key: 'study', t: 'Классы и туры', target: 'sample.study' }] }] } }]} onNavigate={target => setMessage('Split Header: ' + target)} onSignIn={() => setMessage('Split Header: вход')} onSignUp={() => setMessage('Split Header: регистрация')} /><Header items={[{ key: 'example', label: 'Пример', menu: { cols: [{ title: 'Каталог', links: [{ t: 'Поля' }, { t: 'Таблицы' }] }], feature: { title: 'Тур', text: 'Демонстрационные данные', cta: 'Открыть' } } }]} user={{ name: 'Анна' }} notifications searchItems={[{ label: 'Движение по линии', onClick: () => setMessage('Открыта задача') }]} notificationItems={[{ label: 'Проверка завершена', onClick: () => setMessage('Уведомление открыто') }]} userMenuItems={[{ label: 'Профиль', onClick: () => setMessage('Профиль открыт') }]} onNavigate={setMessage} /><Header items={[]} onSignIn={() => setMessage('Открыт вход')} onSignUp={() => setMessage('Открыта регистрация')} /><Pagination compact page={page} total={3} onChange={setPage} /><Stepper current={page - 1} onStepClick={index => setPage(index + 1)} steps={[{ label: 'Первый' }, { label: 'Второй' }, { label: 'Третий' }]} /><p>Текущий шаг и страница: {page}</p></>;
  if (group === 'feedback') content = <><Button onClick={() => toast({ tone: 'success', title: 'useToasts: действие выполнено', description: 'Можно закрыть сообщение' })}>Показать toast</Button>{toaster}{!removed ? <Toast title="Закрываемый Toast" onClose={() => { setRemoved(true); setMessage('Toast закрыт'); }} /> : <Button onClick={() => setRemoved(false)}>Вернуть Toast</Button>}<Alert tone="success" title="Демонстрация завершена" action={<Button onClick={() => setMessage('Действие Alert выполнено')}>Открыть результат</Button>} />{['text', 'circle', 'badge'].map(variant => <Skeleton key={variant} circle={variant === 'circle'} width={variant === 'circle' ? 24 : 100} height={24} style={variant === 'badge' ? { borderRadius: 12 } : undefined} />)}<SkeletonRows rows={2} /><EmptyState error title="Ошибка загрузки" description="Повторите демонстрационную загрузку." action={<Button onClick={() => setMessage('Загрузка повторена')}>Повторить</Button>} /></>;
  if (group === 'overlays') content = <><div className="ts-hstack"><Button onClick={() => setModal('dialog')}>Открыть диалог</Button><Button onClick={() => setModal('danger')}>Опасный диалог</Button><Button onClick={() => setModal('drawer')}>Открыть drawer</Button>{['top', 'right', 'bottom', 'left'].map(placement => <Tooltip key={placement} placement={placement} content={placement}><Button variant="secondary">Tooltip {placement}</Button></Tooltip>)}<Popover align="left" trigger={<Button>Popover слева</Button>}><Button onClick={() => setMessage('Действие Popover выполнено')}>Выполнить</Button></Popover><Popover align="right" trigger={<Button>Popover справа</Button>}><span>Содержимое справа</span></Popover><Menu items={[{ label: 'Открыть' }, { label: 'Недоступно', disabled: true }, { separator: true }, { label: 'Удалить', danger: true }]} onSelect={value => setMessage('Меню: ' + value)} /></div><Dialog open={['dialog', 'danger'].includes(modal)} size="md" variant={modal === 'danger' ? 'danger' : 'default'} title="Демонстрационный диалог" onClose={() => { setModal(null); setMessage('Диалог закрыт'); }} footer={<><Button variant="secondary" onClick={() => setModal(null)}>Отмена</Button><Button onClick={() => { setModal(null); setMessage('Подтверждено'); }}>Подтвердить</Button></>}><Field label="Название"><Input /></Field><Field label="Выбор ресурса в диалоге"><Select options={['Условие', 'Полигон', 'Упражнение']} value={dialogChoice} onChange={setDialogChoice} /></Field><Field label="Несколько ресурсов в диалоге"><MultiSelect options={['Условие', 'Полигон', 'Упражнение']} value={dialogChoices} onChange={setDialogChoices} /></Field><Button onClick={() => setNested(true)}>Вложенный диалог</Button><Dialog open={nested} title="Вложенный диалог" onClose={() => setNested(false)} footer={<Button onClick={() => setNested(false)}>Закрыть вложенный</Button>}>Фокус остаётся внутри верхнего диалога.</Dialog></Dialog><Drawer open={modal === 'drawer'} title="Решение" subtitle="Детали файла" onClose={() => setModal(null)} footer={<Button onClick={() => { setMessage('Drawer: действие выполнено'); setModal(null); }}>Готово</Button>}><Input aria-label="Комментарий" /></Drawer></>;
  if (group === 'quiz') content = <><div className="ts-hstack">{['Один', 'Два', 'Три'].map(label => <QuizOption key={label} multiple selected={selected.includes(label)} label={label} onClick={() => setSelected(selected.includes(label) ? selected.filter(v => v !== label) : [...selected, label])} />)}</div><QuestionNav total={6} current={page} answered={[1, 2]} flagged={[2, 5]} onSelect={setPage} /><p>Ответы: {selected.join(', ') || 'нет'} · вопрос {page}</p></>;
  if (group === 'core') content = <Button icon="plus" onClick={() => setMessage('Действие с декоративной иконкой выполнено')}>Действие с Icon</Button>;
  return <Block title="Работающие состояния и совместимость" actions={<Button size="sm" variant="secondary" onClick={reset}>Сбросить пример</Button>}><div className="ts-vstack">{content}<p role="status">{message}</p></div></Block>;
}
window.CatalogExamples = CatalogExamples;
