package tech.testsys.infra.localization.codegen.emitter

import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.MemberName

/**
 * The generated types of the API in [packageName]. The companion holds the package of the product API
 * `PRODUCT_PACKAGE`, the runtime types generated code uses, the opt-in marker of the internal API, the header of
 * every generated file and
 * `reservedTypeNames`: the simple names a bundle class must not take.
 *
 * @property supportedRegion the generated enum of the regions.
 * @property localization the generated entry point.
 * @property messages the generated object with the MF2 messages of every region.
 */
internal class GeneratedTypes(val packageName: String) {
    val supportedRegion = ClassName("$packageName.bundle", SUPPORTED_REGION)
    val localization = ClassName(packageName, LOCALIZATION)
    val messages = ClassName(packageName, MESSAGES_OBJECT)

    /** Returns the bundle class [className]. */
    fun bundle(className: String): ClassName = ClassName(packageName, className)

    companion object {
        const val PRODUCT_PACKAGE = "tech.testsys.infra.localization"
        const val RUNTIME_PACKAGE = "tech.testsys.infra.localization.runtime"
        const val GENERATED_FILE_HEADER = "Generated by tech.testsys.infra.localization.codegen. Do not edit."

        private const val LOCALIZATION = "Localization"
        private const val MESSAGES_OBJECT = "LocalizationMessages"
        private const val SUPPORTED_REGION = "SupportedRegion"
        private const val MESSAGE_RUNTIME = "MessageRuntime"
        private const val DATE_ZONE = "DateZone"
        private const val INTERNAL_API = "InternalLocalizationApi"
        private const val OPT_IN = "OptIn"

        val runtime = ClassName(RUNTIME_PACKAGE, MESSAGE_RUNTIME)
        val dateZone = ClassName(RUNTIME_PACKAGE, DATE_ZONE)

        // The opt-in marker of the module's internal API; generated internal declarations carry it, generated public
        // ones that use the runtime opt in to it.
        val internalApi = ClassName(PRODUCT_PACKAGE, INTERNAL_API)
        val internalApiAnnotation: AnnotationSpec = AnnotationSpec.builder(internalApi).build()
        val optInInternalApi: AnnotationSpec = AnnotationSpec.builder(ClassName("kotlin", OPT_IN))
            .addMember("%T::class", internalApi)
            .build()
        val zoneId = ClassName("java.time", "ZoneId")
        val instant = ClassName("java.time", "Instant")
        val zonedDateTime = ClassName("java.time", "ZonedDateTime")
        val uLocale = ClassName("com.ibm.icu.util", "ULocale")
        val currencyAmount = ClassName("com.ibm.icu.util", "CurrencyAmount")
        val mapOf = MemberName("kotlin.collections", "mapOf")

        // Generated types, runtime types, types used by generated code and `Companion`: inside `Localization` the name
        // resolves to its companion object, not to a bundle class.
        val reservedTypeNames: Set<String> = setOf(
            LOCALIZATION, MESSAGES_OBJECT, SUPPORTED_REGION, "LocaleData", MESSAGE_RUNTIME, DATE_ZONE, INTERNAL_API,
            "String", "Int", "Number", "Any", "Pair", "Instant", "ZonedDateTime", "ZoneId", "CurrencyAmount", "ULocale",
            "Unit", "Enum", "Suppress", OPT_IN, "Lazy", "Companion",
        )
    }
}
