package tech.testsys.infra.database.internal.jpa.id

import org.hibernate.annotations.IdGeneratorType
import tech.testsys.infra.database.internal.InternalDatabaseApi

/**
 * Marks the id field of a JPA entity as generated by [HibernateSnowflakeIdGenerator]; used together with `@Id`.
 *
 * @since %CURRENT_VERSION%
 */
@IdGeneratorType(HibernateSnowflakeIdGenerator::class)
@Target(AnnotationTarget.FIELD)
@Retention(AnnotationRetention.RUNTIME)
@InternalDatabaseApi
annotation class SnowflakeId
